title: derivative
subtitle: blog on R&D and applied math
email: omarr@simula.no
description: > # this means to ignore newlines until "baseurl:"
  Posts on R&D, artificial intelligence and tech by Omar Richardson,
  
tagline: "Omar Richardson's research blog"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://0mar.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  0mar
linkedin_username: Omar Richardson
permalink: pretty
excerpt_separator: "<!--more-->"
include: ["_pages", "_projects"]
# Build settings
head_scripts:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-include-cache
  - jekyll-feed

author:
  name: "Omar Richardson"
  avatar: "/assets/omar-sc.png"
  bio: "applied mathematician and chief technology officer at simula research laboratory"
  location: "Oslo, Norway"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/0mar"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/omar-richardson"
    - label: "Google scholar"
      icon: "fab fa-fw fa-google-scholar" 
      url: "https://scholar.google.com/citations?user=3SEayEsAAAAJ&hl=en"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      related: true
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      layout: single
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
